### ISSUE TITLE
MAtmos access transformer/mixin clash + Unknown fogcolor error

### ISSUE THREAD

**Issue by MagmaBro123** [mist475/DynamicSurroundings#2]
Title, crash and logs below.

[crash-2024-01-10_12.35.37-client.txt](https://github.com/mist475/DynamicSurroundings/files/13892188/crash-2024-01-10_12.35.37-client.txt)
[fml-client-latest.log](https://github.com/mist475/DynamicSurroundings/files/13892189/fml-client-latest.log)

Modlist in report. Thank Forge for that.

**Comment by mist475** [comment]
This was not an error with lotr as you should've read from the log. MAtmos changes visibility of some methods I overwrite which I didn't know about. Try this version (unzip the file, the jar is inside as github doesn't want to have include jars in comments). PLease let me know if it works and if not please give the new crash error
[DynSurroundTest4Magma.zip](https://github.com/mist475/DynamicSurroundings/files/13904105/DynSurroundTest4Magma.zip)

**Comment by MagmaBro123** [comment]
Well, LOTR was mentioned a lot in the report. I never saw MAtmos in there.

**Comment by MagmaBro123** [comment]
Anyway, game no longer crashes on startup, but does on world load/creation.

[crash-2024-01-11_14.18.13-client.txt](https://github.com/mist475/DynamicSurroundings/files/13908534/crash-2024-01-11_14.18.13-client.txt)

![2024-01-11_14 18 20](https://github.com/mist475/DynamicSurroundings/assets/51277766/11bd4231-a877-4b91-badb-df1359a45de1)

**Comment by mist475** [comment]
Ok, the issue is no longer with MAtmos but with another mod you run. Try this version, 
[DynSurroundTest4Magma2.zip](https://github.com/mist475/DynamicSurroundings/files/13916743/DynSurroundTest4Magma2.zip)
I expect it to fail but it should give a better idea on the cause. Please provide the crash report and the fml-client-latest.log

**Comment by MagmaBro123** [comment]
Still fails

[crash-2024-01-12_12.53.20-client.txt](https://github.com/mist475/DynamicSurroundings/files/13923400/crash-2024-01-12_12.53.20-client.txt)

![2024-01-12_12 53 25](https://github.com/mist475/DynamicSurroundings/assets/51277766/fe381cc8-e65a-4a58-8c77-8cb1da6f07e8)
