### ISSUE TITLE
The game crashes at startup

### ISSUE THREAD

**Issue by Omgise** [mist475/DynamicSurroundings#3]
[fml-client-latest.log](https://github.com/mist475/DynamicSurroundings/files/13938790/fml-client-latest.log)

**Comment by mist475** [comment]
Does this also happen in version 1.0.7.2 and older?

**Comment by Omgise** [comment]
Versions after 1.0.7.2 cause the game to crash

**Comment by mist475** [comment]
You're using too many mods for me to debug easily. Please create a test profile in your launcher of choice with just the latest version of dynamic surroundings and unimixins and then start adding mods until you can replicate the crash as I don't see how what in dynamic surroundings can cause the crash

**Comment by Omgise** [comment]
Ok, I'll give it a try, thanks

**Comment by mist475** [comment]
Try with the latest release, modded compatability should be a bit better now

**Comment by Omgise** [comment]
The game still crashes
[crash-2024-02-10_10.21.47-client.txt](https://github.com/mist475/DynamicSurroundings/files/14227646/crash-2024-02-10_10.21.47-client.txt)

[fml-client-latest.log](https://github.com/mist475/DynamicSurroundings/files/14227648/fml-client-latest.log)

**Comment by mist475** [comment]
I think I know the issue, try without notfine. I already fixed this incompatibility in the angelica version of notfine but I forgot to pr it to the standalone version. Once I have some time I'll open a pr there

**Comment by Omgise** [comment]
Yes, after I tried to disable notfine, the game started normally

**Comment by mist475** [comment]
I have submitted a fix to NotFine, next  NotFine update it should be fixed unless new issues pop up

**Comment by mist475** [comment]
This should be fixed with the release of https://github.com/jss2a98aj/NotFine/releases/tag/0.2.0
