### ISSUE TITLE
Not compatible with LotR Reworked version

### ISSUE THREAD

**Issue by ArchiDreamZ** [mist475/DynamicSurroundings#4]
I only added these two mods
Can't seem to find Biome.
Below is the crash report：
[crash-2024-01-22_22.54.44-client.txt](https://github.com/mist475/DynamicSurroundings/files/14011731/crash-2024-01-22_22.54.44-client.txt)

**Comment by mist475** [comment]
please include your client-latest.log

**Comment by mist475** [comment]
actually I think I know the issue, Reworked probably redoes the way lotr biomes work. Does the issue also happen on version 1.0.7.0?

**Comment by ArchiDreamZ** [comment]
[fml-client-latest.log](https://github.com/mist475/DynamicSurroundings/files/14017695/fml-client-latest.log)

[latest.log](https://github.com/mist475/DynamicSurroundings/files/14017698/latest.log)

**Comment by ArchiDreamZ** [comment]
1.0.7.0 No more crashes

**Comment by mist475** [comment]
Then I think I know the error. I'll add back the original lotr biome retrieval and put it behind a config. That's all the work I'll put into it though as I only support the offical lotr mod, no modified versions

**Comment by mist475** [comment]
I've added a fix, when I have some more content I'll release a new update

**Comment by ArchiDreamZ** [comment]
When I build it myself, I can't download gradle8, can you release a pre-release version?
