### ISSUE TITLE
Is it possible to separate the Presence Footsteps module into a separate mod

### ISSUE THREAD

**Issue by Omgise** [mist475/DynamicSurroundings#6]

**Comment by mist475** [comment]
I am not planning on doing this, I will review the config code to see if the rest can be fully turned off though

**Comment by mist475** [comment]
It took some time before I got around to it. Serverside some code will always run but that shouldn't have a major impact on performance. If you:
- set blocked sounds or culled sounds to 0
- disable the aurora
- disable biome sounds
- disable suppress potion particles
- don't enable the disableWeatherEffects setting
- disable damagepopoffs
- don't enable the potion hud
Then most code doesn't run, including the mixins. Meaning you should only get the presence footsteps portion.

If you want a seperate version of presence footsteps you can try the liteloader release for 1.7.10: https://modrinth.com/mod/presence-footsteps/version/0.5.0+c (I haven't tried this myself)

**Comment by Omgise** [comment]
I once tried the liteloader version of presence footsteps and it would crash the game 😂
