### ISSUE TITLE
How do I configure the block sound and behavior?

### ISSUE THREAD

**Issue by Omgise** [mist475/DynamicSurroundings#7]
![image](https://github.com/mist475/DynamicSurroundings/assets/106000018/ee8da9b6-5162-4cd1-b874-61ab82dbbddb)

**Comment by Omgise** [comment]
Wouldn't it be nice if you knew how to configure it :D

**Comment by Omgise** [comment]
If you know how to configure it, that would be great :D

**Comment by Omgise** [comment]
@mist475 Do you know how to configure footsteps? I want the footsteps of an EFR bed to be the same as the footsteps of a Vanilla bed

**Comment by mist475** [comment]
Remind me again in a few days, I'm currently busy irl

**Comment by Omgise** [comment]
ok

**Comment by mist475** [comment]
Alright, looking at the code, you can configure the block sounds by adding a json file which specifies the block sounds. Examples for this can be found in the https://github.com/mist475/DynamicSurroundings/tree/master/src/main/resources/assets/dsurround/data
folder. For the footsteps system you have to look in the footsteps subfolder. Although the dynamic surroundings wiki is for the 1.12.2 version of the mod this section of it works roughly the same on 1.7.10:
https://dynamicsurroundings.readthedocs.io/en/master/tutorials/footstep.html
https://dynamicsurroundings.readthedocs.io/en/master/tutorials/config_files.html#tutorial-config-files
